#pragma once

#define WINDOW_WIDTH (480)
#define WINDOW_HEIGHT (640)

#define MY_FLIGHT_WIDTH (100)
#define MY_FLIGHT_HEIGHT (100)

#define ENEMY_FLIGHT_WIDTH (100)
#define ENEMY_FLIGHT_HEIGHT (100)
#define MAX_ENEMY_NUM (1)

#define BULLET_WIDTH (20)
#define BULLET_HEIGHT (35)